/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects__get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Project Defaults
         * @description Prefill values for the 'register project' form (dev convenience).
         */
        get: operations["project_defaults_api_v1_projects_defaults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Project */
        post: operations["upload_project_api_v1_projects_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reingest Project */
        post: operations["reingest_project_api_v1_projects__project_id__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Graph */
        get: operations["get_graph_api_v1_projects__project_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_api_v1_projects__project_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Node */
        get: operations["get_node_api_v1_projects__project_id__nodes__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/nodes/{node_id}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Node Columns */
        get: operations["get_node_columns_api_v1_projects__project_id__nodes__node_id__columns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/nodes/{node_id}/column-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Node Column Usage */
        get: operations["get_node_column_usage_api_v1_projects__project_id__nodes__node_id__column_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/nodes/{node_id}/columns/{column}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Column Lineage */
        get: operations["get_column_lineage_api_v1_projects__project_id__nodes__node_id__columns__column__lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analytics */
        get: operations["get_analytics_api_v1_projects__project_id__analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsResponse */
        AnalyticsResponse: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** By Layer */
            by_layer: {
                [key: string]: number;
            };
            /** Column Lineage */
            column_lineage: {
                [key: string]: number;
            };
            /** Materializations */
            materializations: {
                [key: string]: number;
            };
            /** Node Edges */
            node_edges: number;
            /** Column Edges */
            column_edges: number;
            /** Most Used */
            most_used: components["schemas"]["MostUsedModel"][];
            ownership: components["schemas"]["OwnershipStats"];
            /** Dbt Version */
            dbt_version: string | null;
            /** Adapter */
            adapter: string | null;
        };
        /** Body_upload_project_api_v1_projects_upload_post */
        Body_upload_project_api_v1_projects_upload_post: {
            /** Name */
            name: string;
            /** Manifest */
            manifest: string;
            /** Catalog */
            catalog?: string | null;
        };
        /** ColumnEdgeOut */
        ColumnEdgeOut: {
            src: components["schemas"]["ColumnRefOut"];
            dst: components["schemas"]["ColumnRefOut"];
            /** Transform */
            transform: string;
            /** Confidence */
            confidence: string;
        };
        /** ColumnLineageResponse */
        ColumnLineageResponse: {
            root: components["schemas"]["ColumnRefOut"];
            /** Direction */
            direction: string;
            /** Columns */
            columns: components["schemas"]["ColumnRefOut"][];
            /** Edges */
            edges: components["schemas"]["ColumnEdgeOut"][];
            /** Source Columns */
            source_columns: components["schemas"]["ColumnRefOut"][];
            /** Partial */
            partial: boolean;
        };
        /** ColumnLite */
        ColumnLite: {
            /** Name */
            name: string;
            /** Data Type */
            data_type: string | null;
            /** Has Lineage */
            has_lineage: boolean;
        };
        /** ColumnOut */
        ColumnOut: {
            /** Name */
            name: string;
            /** Data Type */
            data_type: string | null;
            /** Description */
            description: string | null;
            /** Tags */
            tags: string[];
            /** Has Lineage */
            has_lineage: boolean;
        };
        /** ColumnRefOut */
        ColumnRefOut: {
            /** Node Id */
            node_id: string;
            /** Column */
            column: string;
            /** Layer */
            layer: string;
        };
        /** ColumnUsageItem */
        ColumnUsageItem: {
            /** Node Id */
            node_id: string;
            /** Used */
            used: number;
            /** Total */
            total: number;
        };
        /** ColumnUsageOut */
        ColumnUsageOut: {
            /** Upstream */
            upstream: components["schemas"]["ColumnUsageItem"][];
            /** Downstream */
            downstream: components["schemas"]["ColumnUsageItem"][];
        };
        /** CreateProject */
        CreateProject: {
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
        /** EdgeOut */
        EdgeOut: {
            /** Src */
            src: string;
            /** Dst */
            dst: string;
        };
        /** GraphNodeOut */
        GraphNodeOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Resource Type */
            resource_type: string;
            /** Layer */
            layer: string;
            /** Materialized */
            materialized: string | null;
            /** Column Lineage Status */
            column_lineage_status: string | null;
            metrics: components["schemas"]["NodeMetricsOut"];
        };
        /** GraphResponse */
        GraphResponse: {
            /** Layers */
            layers: components["schemas"]["LayerOut"][];
            /** Nodes */
            nodes: components["schemas"]["GraphNodeOut"][];
            /** Edges */
            edges: components["schemas"]["EdgeOut"][];
            /** Layer Edges */
            layer_edges: components["schemas"]["LayerEdgeOut"][];
            /** Coverage */
            coverage: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestStatus
         * @enum {string}
         */
        IngestStatus: "pending" | "running" | "ready" | "failed";
        /** LayerEdgeOut */
        LayerEdgeOut: {
            /** Src */
            src: string;
            /** Dst */
            dst: string;
            /** Count */
            count: number;
        };
        /** LayerOut */
        LayerOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Node Ids */
            node_ids: string[];
        };
        /** MetricValueOut */
        MetricValueOut: {
            /** Node Id */
            node_id: string;
            /** Value */
            value: number;
            /** Normalized */
            normalized: number;
        };
        /** MostUsedModel */
        MostUsedModel: {
            /** Node Id */
            node_id: string;
            /** Name */
            name: string;
            /** Layer */
            layer: string;
            /** Downstream Count */
            downstream_count: number;
        };
        /** NodeDetailOut */
        NodeDetailOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Resource Type */
            resource_type: string;
            /** Layer */
            layer: string;
            /** Materialized */
            materialized: string | null;
            /** Schema Name */
            schema_name: string | null;
            /** Database Name */
            database_name: string | null;
            /** File Path */
            file_path: string | null;
            /** Description */
            description: string | null;
            /** Tags */
            tags: string[];
            metrics: components["schemas"]["NodeMetricsOut"];
            /** Columns */
            columns: components["schemas"]["ColumnOut"][];
            /** Parents */
            parents: string[];
            /** Children */
            children: string[];
            /** Column Lineage Status */
            column_lineage_status: string | null;
            /** Sql */
            sql: string | null;
        };
        /** NodeMetricsOut */
        NodeMetricsOut: {
            /** Fan In */
            fan_in: number;
            /** Fan Out */
            fan_out: number;
            /** Upstream Count */
            upstream_count: number;
            /** Downstream Count */
            downstream_count: number;
            /** Degree Centrality */
            degree_centrality: number;
            /** Betweenness */
            betweenness: number;
            /** Hotspot Score */
            hotspot_score: number;
            /** Loc */
            loc: number;
            /** Complexity */
            complexity: number;
            /** Cohesion */
            cohesion: number;
            /** Test Count */
            test_count: number;
            /** Column Count */
            column_count: number;
            /** Owner */
            owner?: string | null;
            /** Owner Share */
            owner_share?: number | null;
            /**
             * Contributor Count
             * @default 0
             */
            contributor_count: number;
            /** Last Author */
            last_author?: string | null;
            /** Last Modified At */
            last_modified_at?: string | null;
        };
        /** OwnerStat */
        OwnerStat: {
            /** Owner */
            owner: string;
            /** Model Count */
            model_count: number;
            /** Avg Share */
            avg_share: number;
        };
        /** OwnershipStats */
        OwnershipStats: {
            /** Tracked */
            tracked: boolean;
            /** Leaderboard */
            leaderboard: components["schemas"]["OwnerStat"][];
            /** By Layer */
            by_layer: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Risk */
            risk: {
                [key: string]: number;
            };
        };
        /** ProjectResult */
        ProjectResult: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            source_type: components["schemas"]["SourceType"];
            /** Source Ref */
            source_ref: string | null;
            /** Manifest Hash */
            manifest_hash: string | null;
            status: components["schemas"]["IngestStatus"];
            /** Error */
            error: string | null;
            /** Ingested At */
            ingested_at: string | null;
            /** Stats */
            stats: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * SourceType
         * @description How a project's artifacts are supplied.
         * @enum {string}
         */
        SourceType: "path" | "upload";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_api_v1_projects__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResult"][];
                };
            };
        };
    };
    create_project_api_v1_projects__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProject"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_defaults_api_v1_projects_defaults_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_project_api_v1_projects_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_project_api_v1_projects_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reingest_project_api_v1_projects__project_id__ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_api_v1_projects__project_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_api_v1_projects__project_id__metrics_get: {
        parameters: {
            query?: {
                metric?: string;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricValueOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_api_v1_projects__project_id__nodes__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_columns_api_v1_projects__project_id__nodes__node_id__columns_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnLite"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_column_usage_api_v1_projects__project_id__nodes__node_id__column_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnUsageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_column_lineage_api_v1_projects__project_id__nodes__node_id__columns__column__lineage_get: {
        parameters: {
            query?: {
                direction?: string;
            };
            header?: never;
            path: {
                project_id: string;
                node_id: string;
                column: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnLineageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytics_api_v1_projects__project_id__analytics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
