"""initial lineage schema

Revision ID: 18ae60d88398
Revises: 
Create Date: 2026-08-13 22:47:43.848751

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '18ae60d88398'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('manifest_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('column_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('src_node', sa.String(length=500), nullable=False),
    sa.Column('src_col', sa.String(length=300), nullable=False),
    sa.Column('dst_node', sa.String(length=500), nullable=False),
    sa.Column('dst_col', sa.String(length=300), nullable=False),
    sa.Column('transform', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_column_edges_dst', 'column_edges', ['project_id', 'dst_node', 'dst_col'], unique=False)
    op.create_index(op.f('ix_column_edges_project_id'), 'column_edges', ['project_id'], unique=False)
    op.create_index('ix_column_edges_src', 'column_edges', ['project_id', 'src_node', 'src_col'], unique=False)
    op.create_table('node_columns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('node_unique_id', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('data_type', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=True),
    sa.Column('has_lineage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'node_unique_id', 'name', name='uq_node_columns_node_name')
    )
    op.create_index(op.f('ix_node_columns_project_id'), 'node_columns', ['project_id'], unique=False)
    op.create_index('ix_node_columns_project_node', 'node_columns', ['project_id', 'node_unique_id'], unique=False)
    op.create_table('node_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('src_id', sa.String(length=500), nullable=False),
    sa.Column('dst_id', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'src_id', 'dst_id', name='uq_node_edges')
    )
    op.create_index('ix_node_edges_project', 'node_edges', ['project_id'], unique=False)
    op.create_index(op.f('ix_node_edges_project_id'), 'node_edges', ['project_id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('unique_id', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('layer', sa.String(length=20), nullable=False),
    sa.Column('materialized', sa.String(length=30), nullable=True),
    sa.Column('schema_name', sa.String(length=300), nullable=True),
    sa.Column('database_name', sa.String(length=300), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fan_in', sa.Integer(), nullable=False),
    sa.Column('fan_out', sa.Integer(), nullable=False),
    sa.Column('upstream_count', sa.Integer(), nullable=False),
    sa.Column('downstream_count', sa.Integer(), nullable=False),
    sa.Column('degree_centrality', sa.Float(), nullable=False),
    sa.Column('betweenness', sa.Float(), nullable=False),
    sa.Column('hotspot_score', sa.Float(), nullable=False),
    sa.Column('column_lineage_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'unique_id', name='uq_nodes_project_unique_id')
    )
    op.create_index(op.f('ix_nodes_project_id'), 'nodes', ['project_id'], unique=False)
    op.create_index('ix_nodes_project_layer', 'nodes', ['project_id', 'layer'], unique=False)
    op.create_table('parse_diagnostics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('node_unique_id', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('unresolved_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parse_diagnostics_project', 'parse_diagnostics', ['project_id'], unique=False)
    op.create_index(op.f('ix_parse_diagnostics_project_id'), 'parse_diagnostics', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parse_diagnostics_project_id'), table_name='parse_diagnostics')
    op.drop_index('ix_parse_diagnostics_project', table_name='parse_diagnostics')
    op.drop_table('parse_diagnostics')
    op.drop_index('ix_nodes_project_layer', table_name='nodes')
    op.drop_index(op.f('ix_nodes_project_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_node_edges_project_id'), table_name='node_edges')
    op.drop_index('ix_node_edges_project', table_name='node_edges')
    op.drop_table('node_edges')
    op.drop_index('ix_node_columns_project_node', table_name='node_columns')
    op.drop_index(op.f('ix_node_columns_project_id'), table_name='node_columns')
    op.drop_table('node_columns')
    op.drop_index('ix_column_edges_src', table_name='column_edges')
    op.drop_index(op.f('ix_column_edges_project_id'), table_name='column_edges')
    op.drop_index('ix_column_edges_dst', table_name='column_edges')
    op.drop_table('column_edges')
    op.drop_table('projects')
    # ### end Alembic commands ###
