"""node ownership fields

Revision ID: df1cae27cde0
Revises: 591f92630c5a
Create Date: 2026-08-22 17:32:10.248309

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df1cae27cde0'
down_revision: str | None = '591f92630c5a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('owner', sa.String(length=200), nullable=True))
    op.add_column('nodes', sa.Column('owner_share', sa.Float(), nullable=True))
    op.add_column('nodes', sa.Column('contributor_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('nodes', sa.Column('last_author', sa.String(length=200), nullable=True))
    op.add_column('nodes', sa.Column('last_modified_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'last_modified_at')
    op.drop_column('nodes', 'last_author')
    op.drop_column('nodes', 'contributor_count')
    op.drop_column('nodes', 'owner_share')
    op.drop_column('nodes', 'owner')
    # ### end Alembic commands ###
