"""add node code/quality metrics + raw_code

Revision ID: 591f92630c5a
Revises: 08cc3fdc0df1
Create Date: 2026-08-14 00:15:43.956573

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '591f92630c5a'
down_revision: str | None = '08cc3fdc0df1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default lets these NOT NULL columns be added to a populated table;
    # ingestion always writes explicit values afterwards.
    op.add_column('nodes', sa.Column('raw_code', sa.Text(), nullable=True))
    op.add_column('nodes', sa.Column('loc', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('nodes', sa.Column('complexity', sa.Float(), nullable=False, server_default='0'))
    op.add_column('nodes', sa.Column('cohesion', sa.Float(), nullable=False, server_default='0'))
    op.add_column('nodes', sa.Column('test_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('nodes', sa.Column('column_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'column_count')
    op.drop_column('nodes', 'test_count')
    op.drop_column('nodes', 'cohesion')
    op.drop_column('nodes', 'complexity')
    op.drop_column('nodes', 'loc')
    op.drop_column('nodes', 'raw_code')
    # ### end Alembic commands ###
