"""model_errors table

Revision ID: a221f380f79a
Revises: df1cae27cde0
Create Date: 2026-08-22 18:57:17.515572

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a221f380f79a'
down_revision: str | None = 'df1cae27cde0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('node_unique_id', sa.String(length=500), nullable=False),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_errors_project_category', 'model_errors', ['project_id', 'category'], unique=False)
    op.create_index(op.f('ix_model_errors_project_id'), 'model_errors', ['project_id'], unique=False)
    op.create_index('ix_model_errors_project_node', 'model_errors', ['project_id', 'node_unique_id'], unique=False)
    op.create_index('ix_model_errors_project_occurred', 'model_errors', ['project_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_errors_project_occurred', table_name='model_errors')
    op.drop_index('ix_model_errors_project_node', table_name='model_errors')
    op.drop_index(op.f('ix_model_errors_project_id'), table_name='model_errors')
    op.drop_index('ix_model_errors_project_category', table_name='model_errors')
    op.drop_table('model_errors')
    # ### end Alembic commands ###
